repos:
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--line-length=120]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  -   id: reorder-python-imports
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.265'
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
    args: ["--ignore-missing-imports"]
    additional_dependencies: ["types-requests"]
- repo: local
  hooks:
  - id: gitchangelog
    language: system
    always_run: true
    pass_filenames: false
    name: Generate changelog
    entry: bash -c "gitchangelog > CHANGELOG.md"
    stages: [commit]
