name: Deploy to PyPI

on:
  push:
    branches: [master]
    tags: ['v*']

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -U twine pre-commit gitchangelog pystache wheel
      - name: Fetch all tags
        run: git fetch --prune --unshallow --tags || true
      - name: Generate changelog
        run: pre-commit run -a gitchangelog || true
      - name: Run pre-commit
        run: pre-commit run -a
      - name: Build wheel
        run: python3 setup.py sdist bdist_wheel
      - name: Deploy to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
